name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Find .npmrc files
        run: find . -name ".npmrc" -type f || true

      - name: Display .npmrc (sanitized)
        run: |
          if [ -f .npmrc ]; then
            # Print lines that do not contain sensitive info like auth tokens
            grep -v "//registry.npmjs.org/:_authToken=" .npmrc || true
          else
            echo ".npmrc not found in the working directory."
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Run semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
